language: generic

os: osx
osx_image: xcode9.4

env:
  global:
    - COLUMNS=240
    - PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig:/usr/local/opt/jpeg-turbo/lib/pkgconfig:$PKG_CONFIG_PATH"
    - HOMEBREW_NO_AUTO_UPDATE=1
    - HOMEBREW_NO_INSTALL_CLEANUP=1

before_install:
  - brew tap lovell/package-libvips-darwin https://github.com/lovell/package-libvips-darwin.git
  - KEEP_DEPENDENCIES=$(brew deps --include-build lovell/package-libvips-darwin/vips)
  - echo "$KEEP_DEPENDENCIES"
  - brew update
  - brew cleanup
  # Remove unused formulae to speed upgrade
  - brew list -1 | grep -Ev ${KEEP_DEPENDENCIES//$'\n'/|} | xargs brew rm -f
  - brew upgrade

install:
  - brew install advancecomp
  # Need to reinstall libtiff and gdk-pixbuf for libjpeg-turbo support
  - brew reinstall --build-from-source lovell/package-libvips-darwin/libtiff
  - brew reinstall --build-from-source lovell/package-libvips-darwin/gdk-pixbuf
  - brew install --build-bottle lovell/package-libvips-darwin/vips

script:
  - ./build/osx.sh

before_cache:
  - brew cleanup

cache:
  directories:
    # Cache downloaded bottles
    - $HOME/Library/Caches/Homebrew

addons:
  artifacts:
    s3_region: eu-west-1
